name: release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: corepack enable pnpm
      - run: npm i -g ovsx@0.8.2
      - run: pnpm install --frozen-lockfile --no-optional
      - run: pnpm run build:minify && pnpm ovsx publish
        working-directory: packages/vscode-vue
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
